### ISSUE TITLE
Draw image on canvas

### ISSUE THREAD

**Issue by AshrayShetty4** [AshtrayShetty/JS-canvas#10]
On clicking **File->Open**, the user should be able to select an image on their computer. On selecting this image, it should be drawn on the canvas over which the user can work on.

**Comment by david-webber** [comment]
This project looks interesting, can I give this a go?

**Comment by AshrayShetty4** [comment]
go ahead!!!

**Comment by david-webber** [comment]
I took a quick look on my lunch break and have the image loading on the canvas at the top left, also I'm not clearing the canvas when the image is loaded so you can load multiple images over each other. Is this the behaviour you're expecting?

I'm back to work now but I will continue again this evening.

Do you have any other requirements for this issue?

Thanks.

**Comment by AshrayShetty4** [comment]
Yes. That's pretty much what I wanted.

Few other requirements (at least for now), would be to provide some coordinates to place the image on (probably a prompt to ask for X and Y distances from the left and top edges of the canvas). 

I'll probably implement the dragging elements around feature later or raise it as an issue.

**Comment by david-webber** [comment]
Okay cool, thanks for the clarification. I will be back on my pc again in a minute so will take a look and hopefully open a PR this evening.
