### ISSUE TITLE
A visual indicator of the cursor on using eraser feature

### ISSUE THREAD

**Issue by AshrayShetty4** [AshtrayShetty/JS-canvas#7]
Currently, the output is displayed only on `mouseup` events. There is no visual indicator of how the output might look like. Although this is fine for features like line, rectangle, ellipse, etc; it's not fine for eraser feature. The user wouldn't know the size of the eraser on increasing or decreasing its size, i.e, they wouldn't know when to stop changing the size of the eraser (which could lead to dissatisfaction from some users).

**Comment by Nopraz** [comment]
Hello, I will try to add this feature

**Comment by AshrayShetty4** [comment]
Yeah sure!!!

**Comment by Nopraz** [comment]
Just did the PR #9 for the feature
